export const icons = {
  bars: 'bars',
  trash: 'trash-o',
  save: 'save',
  tag: 'tag',
  plus: 'plus',
  floppy: 'floppy-o',
  copy: 'copy',
  done: 'check',
  check: 'check-square',
  uncheck: 'square',
  reset: 'rotate-right',
  pen: 'pencil',
  info: 'info',
  eye: 'eye',
  gear: 'gear',
  paste: 'paste',
}
